export const SELECT_ALL_REQUEST = 'SELECT_ALL_REQUEST'
export const SELECT_ALL_SUCCESS = 'SELECT_ALL_SUCCESS'
export const SELECT_ALL_FAIL = 'SELECT_ALL_FAIL'

export const SELECT_SPECS_REQUEST = 'SELECT_SPECS_REQUEST'
export const SELECT_SPECS_SUCCESS = 'SELECT_SPECS_SUCCESS'
export const SELECT_SPECS_FAIL = 'SELECT_SPECS_FAIL'

export const SELECT_COUNTRY_REQUEST = 'SELECT_COUNTRY_REQUEST'
export const SELECT_COUNTRY_SUCCESS = 'SELECT_COUNTRY_SUCCESS'
export const SELECT_COUNTRY_FAIL = 'SELECT_COUNTRY_FAIL'

export const SELECT_PAY_CONDS_REQUEST = 'SELECT_PAY_CONDS_REQUEST'
export const SELECT_PAY_CONDS_SUCCESS = 'SELECT_PAY_CONDS_SUCCESS'
export const SELECT_PAY_CONDS_FAIL = 'SELECT_PAY_CONDS_FAIL'

export const SELECT_LOGIN_REQUEST = 'SELECT_LOGIN_REQUEST'
export const SELECT_LOGIN_SUCCESS = 'SELECT_LOGIN_SUCCESS'
export const SELECT_LOGIN_FAIL = 'SELECT_LOGIN_FAIL'